### ISSUE TITLE
Unable to compile for 4.17

### ISSUE THREAD

**Issue by alios** [BoredEngineer/MMT_Plugin#2]
Hi! 

Tried to compile the plugin with Engine 4.17 which seems to be no longer possible because basicly of these type of errors: 

*  An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
* Cannot expose property to blueprints in a struct that is not a BlueprintType

Here is the logfile from my try to build the plugin within the 4.17 codebase:

```
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(42) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(45) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(48) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(75) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(18) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(21) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(24) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(27) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetPassive.h(46) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetPassive.h(49) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTFrictionSolverComponent.h(52) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPawn.h(34) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTSuspensionStackComponent.h(20) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(17) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(17) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackPhysicalSurfaceFriction.PhysicalSurface
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(19) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(19) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackPhysicalSurfaceFriction.FrictionScaleFactor
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(21) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(21) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackPhysicalSurfaceFriction.RollingFrictionCoefficient
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(38) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(38) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackFrictionSettings.MuXStatic
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(40) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(40) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackFrictionSettings.MuXKinetic
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(42) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(42) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackFrictionSettings.bUseAnisotropicFriction
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(44) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(44) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackFrictionSettings.MuYStatic
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(46) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(46) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackFrictionSettings.MuYKinetic
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(48) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(48) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. MMTTrackFrictionSettings.TrackPhysicalSurfaceFrictionCoefficients
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(48) : LogCompile: Error: Type 'TArray<FMMTTrackPhysicalSurfaceFriction>' is not supported by blueprint. MMTTrackFrictionSettings.TrackPhysicalSurfaceFrictionCoefficients
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(72) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(72) : LogCompile: Error: Type 'FMMTTrackFrictionSettings' is not supported by blueprint. MMTTrack.TrackFrictionSettings
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(74) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(17) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(17) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TrackSets.TrackName
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(19) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(19) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TrackSets.bDisabled
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(21) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(21) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TrackSets.bDebugMode
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(23) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(23) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TrackSets.ReferenceFrameComponentName
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(25) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(25) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TrackSets.TrackClass
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(42) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TracksConfig.bEnableTracks
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(44) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. TracksConfig.TrackSets
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(44) : LogCompile: Error: Type 'TArray<FTrackSets>' is not supported by blueprint. TracksConfig.TrackSets
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(54) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(54) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. WheelSets.WheelName
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(56) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(56) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. WheelSets.bDisabled
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(58) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(58) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. WheelSets.bDebugMode
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(60) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(60) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. WheelSets.ReferenceFrameComponentName
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(76) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. WheelsConfig.bEnableWheels
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(78) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. WheelsConfig.WheelSets
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(78) : LogCompile: Error: Type 'TArray<FWheelSets>' is not supported by blueprint. WheelsConfig.WheelSets
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(89) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(89) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. PassiveSets.SurfaceName
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(91) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(91) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. PassiveSets.bDisabled
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(93) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(93) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. PassiveSets.bDebugMode
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(95) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(95) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. PassiveSets.ReferenceFrameComponentName
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(112) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. PassiveSurfaceConfig.bEnablePassiveSurfaces
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(114) : LogCompile: Error: Cannot expose property to blueprints in a struct that is not a BlueprintType. PassiveSurfaceConfig.PassiveSets
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(114) : LogCompile: Error: Type 'TArray<FPassiveSets>' is not supported by blueprint. PassiveSurfaceConfig.PassiveSets
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionComponent.h(35) : LogCompile: Error: Type 'FTracksConfig' is not supported by blueprint. MMTVehicleSuspensionComponent.TracksConfiguration
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionComponent.h(38) : LogCompile: Error: Type 'FWheelsConfig' is not supported by blueprint. MMTVehicleSuspensionComponent.WheelsConfiguration
2>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionComponent.h(41) : LogCompile: Error: Type 'FPassiveSurfaceConfig' is not supported by blueprint. MMTVehicleSuspensionComponent.PassiveSurfacesConfiguration
```

I was able to fix the the missing-category type of errors by adding a category to those `UPROPERTY()`s but I'am unsure about the other type of error.

**Comment by BoredEngineer** [comment]
This should help:
https://answers.unrealengine.com/questions/338361/why-isnt-my-struct-exposed-to-blueprint.html

I guess these changes where semi-necessary before but where not enforced. Thank you for letting me know about these issues, will port everything to 4.17 at some point.

**Comment by BoredEngineer** [comment]
Resolved, commiting 4.17 version now.

**Comment by alios** [comment]
Hi! 

Tried it by just installing into a projects plugin folder, but I still get a message on opening the project stating:

```
This project required the 'MMT'plugin, which is not compatible with the current engine version.

Would you like to disable it? You will no longer be able to open any assets created using it.
```

Trying to compile it within the unreal engine (4.17) source code I get a bunch of errors about Category specifiers:

```
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(42) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(45) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(48) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPhysicalSurfaceFrictionCoefficient.h(75) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(18) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(21) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(24) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetBase.h(27) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetPassive.h(46) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Private/MMTFrictionSetPassive.h(49) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTFrictionSolverComponent.h(52) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTPawn.h(34) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTSuspensionStackComponent.h(20) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(17) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(19) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(21) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(38) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(40) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(42) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(44) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(46) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(48) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(72) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTTrack.h(74) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(17) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(19) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(21) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(23) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(25) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(54) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(56) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(58) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(60) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(89) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(91) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(93) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>E:/UnrealEngine/Engine/Plugins/Runtime/MMT/Source/MMT/Public/MMTVehicleSuspensionStructs.h(95) : LogCompile: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
4>EXEC : error : UnrealHeaderTool failed for target 'UE4Editor' (platform: Win64, module info: E:\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest, exit code: OtherCompilationError (5)).
4>E:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(49,5): error MSB3073: Der Befehl "..\..\Build\BatchFiles\Rebuild.bat UE4Editor Win64 Development -waitmutex" wurde mit dem Code -1 beendet.
4>Die Erstellung des Projekts "UE4.vcxproj" ist abgeschlossen -- FEHLER.
========== Alles neu erstellen: 3 erfolgreich, 1 fehlerhaft, 0 übersprungen ==========
```

**Comment by BoredEngineer** [comment]
Are you using launcher version of 4.17 source or one from GitHub?

**Comment by alios** [comment]
I use the github sources (for trying to compile it within the engine project) as well as using the binary version of the plugin with in  a project.

**Comment by BoredEngineer** [comment]
@alios Just to clear up - you are using github version of UE4 and installing plugin as engine plugin, not as project plugin?
If I search for this error on wiki, this is what I find:
https://answers.unrealengine.com/questions/438712/uht-inconsistency-can-prevent-projects-from-buildi.html

Anyway, just adding some arbitrary category should fix it, like this:
UPROPERTY(... Category = "My Category", ...))

I don't have a setup with a github source of UE4, would take some time to replicate it. Try adding category into property specifier - it should work.
